"""remove enums

Revision ID: 729cbfef29cc
Revises: 72da993b9287
Create Date: 2023-07-05 14:34:55.223928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729cbfef29cc'
down_revision = '72da993b9287'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
