"""added nullable for user_id

Revision ID: 85345f220278
Revises: 729cbfef29cc
Create Date: 2023-07-05 14:46:50.863871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85345f220278'
down_revision = '729cbfef29cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
